version: 2.1
jobs:
  build:
    docker:
      - image: nixos/nix:2.3
    steps:
      - checkout
      - restore_cache:
          key: nix-store
      - run: nix-shell --run "exit"
      - save_cache:
          paths:
            - /nix/store
          key: nix-store
      - run: echo "hello world"
