version: 2.1
jobs:
  build:
    docker:
      - image: nixos/nix:2.3
    steps:
      - restore_cache:
          key: nix-store
      - run: nix-env -i git openssh
      - checkout
      - run: git --help
      - run: nix-shell -v --run "echo hello from nix"
      - save_cache:
          paths:
            - /nix/store
          key: nix-store
      - run: echo "hello world"
