version: 2.1
jobs:
  build:
    docker:
      - image: nixos/nix:2.3
    steps:
      - checkout
      - restore_cache:
          key: nix-store--{{ .Branch }}-{{ checksum "shell.nix" }}
      - run: nix-shell -v --run "echo hello from nix"
      - save_cache:
          paths:
            - /nix/
          key: nix-store--{{ .Branch }}-{{ checksum "shell.nix" }}
      - run: echo "hello world"
