version: 2.1
jobs:
  build:
    docker:
      - image: nixos/nix:2.3
    steps:
      - run: nix-env -i git
      - checkout
      - run: nix-shell --run "echo 'hi from nix-shell'"
      - run: echo "hello world"
